# Lab 02 - Numpy

Name: Jimmy Pronchick  
Class: CSCI349 2023SP - Intro to Data Mining  
Instructor: Brian King

In [4]:
#setup
import sys
import numpy as np
print(sys.version)
print("numpy: " + np.__version__)

3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
numpy: 1.23.5


1)[P] Create a 100000x 75 matrix of zeros, stored as X.Then,print out the shapeof the matrix, the base data type, the individual item size in the array, and the total size of the array in bytes(as an integer). Also, print out the total sizein megabyteswith 3 significant digits.

In [29]:
X = np.zeros((100000,75))
print(X.size)
print(X.shape)
print(X.dtype)
print(X.itemsize)
print(X.itemsize*X.size)
print("%.3f mb"%((X.itemsize*X.size)/1000000))

7500000
(100000, 75)
float64
8
60000000
60.000 mb


2)[P] Resize X to have the same number ofelements, but with 100 columns.Show the shape. Show the number of bytes (whichshould be the same as the previous answer)

In [31]:
np.reshape(X,(75000,100))
print(X.shape)
print(X.itemsize*X.size)

(100000, 75)
60000000


3)[P] Redo #1, but use a base datatype of 16-bit integers.

In [33]:
X = np.zeros((100000,75),np.int16)
print(X.size)
print(X.shape)
print(X.dtype)
print(X.itemsize)
print(X.itemsize*X.size)
print("%.3f mb"%((X.itemsize*X.size)/1000000))

7500000
(100000, 75)
int16
2
15000000
15.000 mb


4)[P] How many dimensions does X have? Answer using the appropriate property of np.ndarrayobjects.

In [37]:
X.ndim

2

[P] Enter the following Python list in your cell: str_nums = ['2.14', '-9.300', '42']Convert this to a numpyarray named X. What is the base type? Show the contents of X.We want numeric representation. So, convert Xto an array of single precision floating point numbers. (HINT: use astype). Show Xagain.

In [43]:
str_nums = ['2.14', '-9.300', '42']
X = np.asarray(str_nums)
print(X.dtype)
print(X)
X.astype(np.single)

<U6
['2.14' '-9.300' '42']


array([ 2.14, -9.3 , 42.  ], dtype=float32)

6)[P] Copy the three definitions above forthe Python listsdays, scores_1, and scores_2. Create a numpyarray called scoresthat has scores_1as the first row and scores_2as the second row using np.concatenate. Then, change daysinto a np.arrayfrom the list days. Show the contents of scoresand days, and output their shape. 

In [248]:
days = ["Mon","Tue","Wed","Thu","Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 9.5, 8.75, 7.25]

In [249]:
scores = np.reshape(np.concatenate((scores_1, scores_2)),(2,5))
daysNP= np.asarray(days)
print(scores)
print(scores.shape)
print(daysNP)
daysNP.shape

[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.    9.5   8.75  7.25]]
(2, 5)
['Mon' 'Tue' 'Wed' 'Thu' 'Fri']


(5,)

[P] Repeat the previous problem with the creation of scores fromthe Python lists scores_1and scores_2, but now doit with np.vstack. The array should be identical.

In [250]:
scoresV = np.vstack((scores_1,scores_2))
print(scoresV.shape)
scoresV

(2, 5)


array([[ 9.5 ,  8.75,  8.  , 10.  ,  7.75],
       [ 9.  ,  8.  ,  9.5 ,  8.75,  7.25]])

8)[P/M] Compare the result of the expression days == "Fri" if the variable days was a Python list as entered above, vs. days being a numpyarray.  What is the differencein the result? In general, how does numpy deal with standard comparison operators?

In [251]:
print(days=="Fri")
print(daysNP=="Fri")

False
[False False False False  True]


The ndarray applies the comparison operator to each element in the array, while with a python list, one comparison is made between the whole list and the string. In general, numpy applies comparison operators element-wise throughout arrays.

9)[P] The scores array represents quizzes that are out of 10 pts. Show the scores array scaled to be out of 100 pts (but do not change scores itself.)

In [252]:
scores * 10.0

array([[ 95. ,  87.5,  80. , 100. ,  77.5],
       [ 90. ,  80. ,  95. ,  87.5,  72.5]])

10)[P] Select the scores that fell on Tuesday.

In [253]:
scores[:,daysNP=="Tue"]

array([[8.75],
       [8.  ]])

11)[P] Select all of the scores that are NOT on Tuesday(Hint –look up the ~operator)

In [254]:
scores[:,~(daysNP=="Tue")]

array([[ 9.5 ,  8.  , 10.  ,  7.75],
       [ 9.  ,  9.5 ,  8.75,  7.25]])

12)[P] Select the scores that were on Tuesday or Thursday

In [255]:
scores[:,(daysNP=="Tue")|(daysNP=="Thu")]

array([[ 8.75, 10.  ],
       [ 8.  ,  8.75]])

13)[P] Show the minimum and maximum scores for the entire array of scores

In [256]:
print("min = {}".format(scores.min()))
print("max = {}".format(scores.max()))

min = 7.25
max = 10.0


14)[P] Show the maximumscores for each week as a new array. The result should have the samedimensions (hint –use the keepdimsparameterof np.max). Your result should be something like:

In [257]:
scores.max(axis=1,keepdims=True)

array([[10. ],
       [ 9.5]])

15)[P] Report the day that the maximumscore occurred each week. (HINT: use argmaxand use that result to index days.)

In [258]:
daysNP[np.argmax(scores,axis=1,keepdims=True)]

array([['Thu'],
       ['Wed']], dtype='<U3')

16)[P] Report the meanof the scores of each week

In [259]:
scores.mean(axis=1,keepdims=True)

array([[8.8],
       [8.5]])

17)[P] Suppose the lowest score was dropped from each week. Report the meanof each week, but without the minimum scorefor that week.

In [272]:
#return scores with lowest scores each week dropped
scoresDropped = np.reshape(scores[np.where(scores>scores.min(axis=1,keepdims=True))],(2,4))
print(scoresDropped)

#calculate mean with new array
scoresDropped.mean(axis=1,keepdims=True)

[[ 9.5   8.75  8.   10.  ]
 [ 9.    8.    9.5   8.75]]


array([[9.0625],
       [8.8125]])

18)[P] Show the number of scores that were > 9 each week as an array.

In [271]:
np.where(scores>9,1,0).sum(axis=1,keepdims=True)

array([[2],
       [1]])

Copy and paste this code into a cell:

In [274]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
X

array([[48, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

19)[P] Select the first row of X

In [276]:
X[0,:]

array([48, 84, 39, 54, 77])

20)[P] Select the last column of X

In [292]:
X[:,-1:]

array([[77],
       [27],
       [59],
       [48],
       [39],
       [81],
       [66],
       [61],
       [14],
       [32]])

21)[P] Select the first AND last column of X

In [289]:
X[:,0:5:4]

array([[48, 77],
       [25, 27],
       [31, 59],
       [93, 48],
       [51, 39],
       [68, 81],
       [ 4, 66],
       [76, 61],
       [47, 14],
       [97, 32]])

22)[P] Select every other row of X

In [293]:
X[0:10:2]

array([[48, 84, 39, 54, 77],
       [31, 44, 31, 27, 59],
       [51, 77, 38, 35, 39],
       [ 4,  3, 20, 13, 66],
       [47, 29, 82, 88, 14]])

23)[P] Show the transpose of X, but don't change X itself

In [311]:
X.T
#accidently reran this cell after incrementing the first value so 0,0 is 49 instead of 48

array([[49, 25, 31, 93, 51, 68,  4, 76, 47, 97],
       [84, 16, 44, 70, 77, 12,  3, 82, 29, 13],
       [39, 50, 31, 81, 38,  1, 20, 15, 82, 70],
       [54, 24, 27, 74, 35, 76, 13, 72, 88, 96],
       [77, 27, 59, 48, 39, 81, 66, 61, 14, 32]])

24)[P] Select the first column of X and set the result to new variable Y.

In [306]:
Y = X[:,0:1]
Y

array([[48],
       [25],
       [31],
       [93],
       [51],
       [68],
       [ 4],
       [76],
       [47],
       [97]])

25)[P] Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change?THIS IS AN IMPORTANT OBSERVATION WHEN DEALING WITH SELECTING DATA!

In [307]:
Y[0] +=1
X[0,0]

49

26)[P] Repeat exercise 23, but ensure that Y is assigned a copyof the selected data. Increment the first value of Y again and ensure that the corresponding value of X did not change.

In [316]:
Y = np.copy(X.T)
Y[0,0]+=1
print(Y)
X

[[50 25 31 93 51 68  4 76 47 97]
 [84 16 44 70 77 12  3 82 29 13]
 [39 50 31 81 38  1 20 15 82 70]
 [54 24 27 74 35 76 13 72 88 96]
 [77 27 59 48 39 81 66 61 14 32]]


array([[49, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

27)[P] Create an array that contains the sequence ofnumbers 0, 0.1, 0.2, ... 9.8, 9.9 using arange, as a 10x10 matrix, stored as X.(HINT: Use np.arange)

In [336]:
X= np.arange(0.0, 10.0, 0.1).reshape(10,10)
X

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

28)[P] Set the RNG seed to 1234. Then create an array X of 100 uniformly distributed numbers, with all values between 1.0 and 10.0.Then, show the mean, the median, the minimum and maximum values of X.

In [3]:
np.random.seed(1234)
X = np.linspace(1.0, 10.0, 100)
print(X[:10])
print("Median: {}".format(np.median(X)))
print("Min: {}".format(X.min()))
print("Max: {}".format(X.max()))

[1.         1.09090909 1.18181818 1.27272727 1.36363636 1.45454545
 1.54545455 1.63636364 1.72727273 1.81818182]
Median: 5.5
Min: 1.0
Max: 10.0


29)[M] Define what is meant by a normal distribution. What are the parameters of a normal distribution? 

A normal distribution is a statistical probability distribuition where the observations are clustered symmetrically around the mean value. There are less observations further from the mean value. The parameters of a normal distribution are the mean and standard deviation.

30)[M] In simple terms, using a normal distribution, what does the Law of Large Numberstell us? 

The law of large numbers tells us that as the sample size grows, the sample increasingly resembles a normal distribution (aka the average of the population).

31)[P] Write a function called test_normal_dist. The purpose of this function is to evaluate the law of large numbers. It should have four parameters:mu= mean of distribution sd= standard deviation vec_length= length of the vector to generate randomly from a normal distribution,with mu and sd as parameters num_trials= number of times to repeat the experiment 
The function should behave as follows. First, initialize the seed value to 1234,before your loop. Then, loop for num_trials, generating vec_lengthnumbers from a normal distribution. Compute the meanof that vector,then compute its deviation(absolute value of the observed mean -expected mean). This should be repeated for all trials. Return the averageof this deviation over all trials.

In [31]:
def test_normal_dist(mu,sd,vec_length, num_trials):
    np.random.seed(1234)
    deviation = 0.0
    i=0
    while i<num_trials:
        i+=1
        my_dist = np.random.normal(mu,sd,vec_length)
        vec_mean = my_dist.mean()
        deviation += np.abs(vec_mean) - mu 
    return deviation/num_trials

32)[P] Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Reportthe results as a numpyarray with two dimensions. the first being the vector length, and the second being the average deviation resulting from your test_normal_distfunction.

In [47]:
results = []
vec_length = 10
while vec_length <1000000:
    results.append(vec_length)
    results.append(test_normal_dist(10,2,vec_length,100))
    vec_length *=10

#numpy was determined to put everything in scientific notation, line below stops that
#https://stackoverflow.com/questions/9777783/suppress-scientific-notation-in-numpy-when-creating-array-from-nested-list
np.set_printoptions(suppress=True)
#deviation decreases as vector length increases
np.reshape((np.asarray(results)), (5,2))

array([[    10.        ,      0.03148116],
       [   100.        ,      0.03225292],
       [  1000.        ,      0.00197142],
       [ 10000.        ,     -0.00062523],
       [100000.        ,      0.00014231]])