# Lab 01 - Getting Started

Name: Jimmy Pronchick  
Class: CSCI349 2023SP - Intro to Data Mining  
Instructor: Brian King

In [2]:
import sys

2. [M] Did you read the syllabus? All of it? Do you understand and agree to abide by the cheating rules? Write a sentence clearly indicating your commitment to not cheating.

I understand and agree to abide by the cheating rules outlined in the syllabus.

3.[M] What are you hoping to get out of this course?

I'm especially interested in machine learning applications in natural language processing, but I'm hoping to gain a deeper understanding of how ML algorithms work and why certain algorithms are better suited for certain applications. My main goals for the course are to learn to speak intelligently about ML and to develop ideas for projects to explore in grad school (and learn the tools to do so).

4.[P] Print the Python version (available in syspackage)

In [3]:
print(sys.version)

3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]


5.[P] Create a Python list of 10000 random integers in the range 1to 100 using the randompackage. Name the list x_list.

In [79]:
import random

x_list = []
i=0
while i<1000:
    x_list.append(random.randint(1,100));
    i+=1
print(x_list)

[57, 29, 66, 66, 1, 35, 34, 54, 28, 81, 39, 68, 46, 31, 11, 75, 38, 32, 17, 50, 43, 51, 31, 26, 23, 47, 76, 66, 12, 59, 57, 28, 66, 55, 13, 7, 22, 68, 90, 67, 53, 30, 63, 37, 49, 39, 10, 90, 77, 82, 29, 2, 29, 5, 96, 59, 38, 6, 96, 86, 72, 42, 32, 36, 47, 49, 17, 82, 19, 7, 62, 62, 79, 73, 78, 50, 79, 16, 97, 94, 29, 64, 32, 90, 25, 55, 14, 25, 63, 11, 78, 35, 66, 60, 36, 75, 22, 24, 29, 93, 48, 82, 26, 46, 91, 27, 39, 86, 79, 41, 54, 89, 2, 72, 34, 14, 90, 29, 31, 41, 61, 12, 18, 46, 37, 44, 32, 98, 17, 9, 22, 82, 41, 66, 35, 66, 100, 64, 88, 55, 97, 46, 42, 62, 24, 39, 34, 91, 37, 35, 84, 22, 69, 68, 46, 33, 51, 83, 94, 54, 77, 50, 3, 96, 22, 40, 14, 74, 2, 49, 25, 42, 92, 48, 24, 77, 71, 92, 4, 83, 65, 43, 93, 38, 95, 59, 89, 10, 66, 74, 31, 73, 93, 52, 18, 20, 3, 22, 42, 4, 58, 73, 22, 78, 28, 8, 78, 31, 8, 78, 65, 97, 90, 5, 88, 19, 63, 48, 90, 4, 74, 68, 29, 72, 86, 99, 21, 81, 95, 94, 54, 58, 76, 16, 12, 58, 87, 79, 69, 28, 43, 63, 76, 74, 2, 20, 15, 31, 9, 25, 13, 41, 13, 81, 2

6.[P] What is the minimum valueof x_list? What is the maxvalue? What is the mode? 

In [80]:
from statistics import mode

print("The minimum value of x_list is {}.".format(min(x_list)))
print("The maximum value of x_list is {}.".format(max(x_list)))
print("The mode of x_list is {}.".format(mode(x_list)))

The minimum value of x_list is 1.
The maximum value of x_list is 100.
The mode of x_list is 66.


7.[P] Write a function to take a list of numbersas a parameter, and return the average of the list. Then, use your function to report the average valueof x_list,printed as a float with 2 places of precision.

In [81]:
def avgList(num_list):
    sum = 0.0
    for item in num_list:
        sum+=item
    return (sum/len(num_list))
print("%.2f"%avgList(x_list));

49.94


8.[P] Create a list called x_hist that represents a histogram, i.e. a distribution of the numerical data, of x_list. Each entry in x_hist should contain the frequency of data over a bin width of 10. So,for example,x_hist[0]represents the frequency of numbers between 1-10, x_hist[1]is the frequency of numbers between 11-20, and so on.Be sure to print x_histat the end.(Do NOT use numpy!)

In [82]:
x_hist = []
for i in range(1,11):
    bin_max = i*10
    bin_width = 10
    x_hist.append(len([num for num in x_list if (num <= bin_max and num > bin_max-bin_width)]))
print(x_hist)

[96, 95, 112, 113, 102, 91, 102, 95, 93, 101]


9.[M] What is numpy? What are its strengths? Does it have any weaknesses?

Numpy is a Python library optimized for data science. It works well with large amounts of dense data due to its support of multi-dimensional arrays. Numpy arrays are useful when you have a large amount of data of all the same type. If you are looking to analyze a mixed dataset, a regular python list will work better, since ndarray hold data of all the same type.

10.[P] Import the numpypackage as np and print the numpyversion

In [83]:
import numpy as np
print(np.__version__)

1.23.5


11.[M] What is the primary object type in numpy? Can it store data of different types? Discuss.

The primary object type in numpy is the homogenous multidimensional array (or ndArray). The data in the array must all be the same type.

12.[M] Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss how the type system is different than the built-in types intand floatin Python.

Numpy can handle standard Python data types in addition to its own types such as numpy.int32, numpy.int16, and numpy.float64.

13.[P] Research how to use numpyto compute the same resultas problem 8 above. (HINT: np.histogram)

In [84]:
np_hist, bin_edges = (np.histogram(x_list))
print(np_hist)

[ 96  95 112 113 102  91 102  95  93 101]


14.[P]Create a numpyarray from x_list. Reassign it as x_list. Show the contentsof the first 20 entries.

In [85]:
x_list = np.asarray(x_list)
print(x_list[:20])

[57 29 66 66  1 35 34 54 28 81 39 68 46 31 11 75 38 32 17 50]


15.[P] Redo the previous exercise, but set the data type of each value to 'float32'

In [86]:
x_list = np.asarray(x_list,dtype=np.float32)
print(x_list[:20])

[57. 29. 66. 66.  1. 35. 34. 54. 28. 81. 39. 68. 46. 31. 11. 75. 38. 32.
 17. 50.]


16.[P] Create a length 10 integer array filled with zeros

In [87]:
zero_array = np.zeros(10).astype(int)
print(zero_array)

[0 0 0 0 0 0 0 0 0 0]


17.[P] Create a float array of 3 rows and 4 columns, all initialized to one.

In [88]:
one_array = np.ones((3,4),float)
print(one_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


18.[P] Create an array of 20 values, evenly spaced between 1 and 3 (HINT –look at np.linspace)

In [89]:
print(np.linspace(1,3,20))

[1.         1.10526316 1.21052632 1.31578947 1.42105263 1.52631579
 1.63157895 1.73684211 1.84210526 1.94736842 2.05263158 2.15789474
 2.26315789 2.36842105 2.47368421 2.57894737 2.68421053 2.78947368
 2.89473684 3.        ]


19.[P] Set the numpyrandom seed to the value 12345, then create a 10x5 array of random integers on the interval [10, 50), assigned to x_mat

In [90]:
np.random.seed(12345)
x_mat=np.random.randint(10,50, size=(10, 5))
print(x_mat)

[[44 47 39 11 46]
 [47 44 39 11 24]
 [37 26 19 21 23]
 [20 27 28 48 17]
 [49 33 39 41 43]
 [37 33 46 10 13]
 [15 25 21 24 27]
 [15 44 18 15 44]
 [15 29 22 24 26]
 [37 48 34 42 15]]


20.[P] Use slicing to select and show the first and last row of x_mat

In [91]:
print(x_mat[0:10:9])

[[44 47 39 11 46]
 [37 48 34 42 15]]


21.[P] Now, show the first, third and fifth column of x_mat

In [92]:
print(x_mat[:,0:5:2])

[[44 39 46]
 [47 39 24]
 [37 19 23]
 [20 28 17]
 [49 39 43]
 [37 46 13]
 [15 21 27]
 [15 18 44]
 [15 22 26]
 [37 34 15]]


22.[P] Show the sum of each row. Your output should appear like this:

In [93]:
for i in range(0,10):
    print("{} {}".format(i,x_mat[i].sum()))

0 187
1 165
2 126
3 140
4 205
5 139
6 112
7 136
8 116
9 176
